feat: install codex

diff --git a/.github/workflows/raft.build.yml b/.github/workflows/raft.build.yml
--- a/.github/workflows/raft.build.yml
+++ b/.github/workflows/raft.build.yml
@@ -43,12 +43,18 @@ jobs:
         run: |
           set -e -o pipefail
 
+          if [[ ! -s raft.build/.codex_version ]]; then
+              echo "ERROR: .codex_version file not found or is empty"
+              exit 1
+          fi
           if [[ ! -s raft.build/.raft_daemon_version ]]; then
               echo "ERROR: .raft_daemon_version file not found or is empty"
               exit 1
           fi
-          ver_raft_daemon="$(tr -d '\r\n\t\f\v ' < raft.build/.raft_daemon_version)"
 
+          ver_codex="$(tr -d '\r\n\t\f\v ' < raft.build/.codex_version)"
+          ver_raft_daemon="$(tr -d '\r\n\t\f\v ' < raft.build/.raft_daemon_version)"
+          echo "ver_codex=${ver_codex}" >> "$GITHUB_OUTPUT"
           echo "ver_raft_daemon=${ver_raft_daemon}" >> "$GITHUB_OUTPUT"
 
       - name: Build and push by digest
@@ -56,6 +62,7 @@ jobs:
         uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
         with:
           build-args: |
+            ver_codex=${{ steps.chores.outputs.ver_codex }}
             ver_raft_daemon=${{ steps.chores.outputs.ver_raft_daemon }}
           context: "{{defaultContext}}:raft.build"
           file: raft-daemon.Dockerfile
